name: GitHub Actions Demo
run-name: Github Action env demoðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: printenv
      - name: Operating System it is running 
        run: ${{ RUNNER_OS }}
